# Generated by Django 4.1.3 on 2023-03-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt_hint_fr',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
