# Generated by Django 4.1.3 on 2023-03-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_prompt_hint_fr_alter_question_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt_hint_fr',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
