# Generated by Django 4.1.3 on 2023-03-07 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_question_prompt_hint_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prerequisite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
