# Generated by Django 4.1.3 on 2023-03-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='prompt_hint_en',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
