# Generated by Django 4.1.3 on 2023-03-07 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_question_prompt_en_question_prompt_hint_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
    ]
