# Generated by Django 4.1.3 on 2023-03-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_question_prerequisite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='prompt_hint_en',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt_hint_fr',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
