# Generated by Django 4.1.7 on 2023-03-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='latest_answer',
        ),
    ]
