# Generated by Django 4.1.3 on 2023-03-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_answer_latest_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prompt_hint_en',
            new_name='hint_en',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='prompt_hint_fr',
            new_name='hint_fr',
        ),
    ]
