# Generated by Django 4.1.7 on 2023-03-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
    ]
