# Generated by Django 4.1.7 on 2023-05-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_type_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('binary', 'binary'), ('binary_multiple', 'binary_multiple'), ('number', 'number'), ('number_multiple', 'number_multiple'), ('multiple_number', 'multiple_number'), ('multiple_binary', 'multiple_binary')], max_length=50),
        ),
    ]
